language:       php

sudo:           false

php:
  - 7.1

env:
  - DB=sqlite

branches:
  only:
    - gh-pages
    - /.*/

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer selfupdate
  - composer update $COMPOSER_FLAGS

script:
  - bin/phpunit
