cmf_core:
    persistence:
        phpcr: ~

    publish_workflow:
        enabled: false

cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 200
            router.default:             100

