security:
    providers:
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|img|static|js)/
            security: false
        main:
            anonymous: ~
