app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
PrestaSitemapBundle:
    resource:             "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:               /

liip_theme:
    resource:             "@LiipThemeBundle/Resources/config/routing.xml"
    prefix:               /theme

